enum ActionTypes {
  CREATE_NEW_TEST = "CREATE_NEW_TEST",
  SET_TEST_EDITOR_DATA = "SET_TEST_EDITOR_DATA",
  ADD_TEST_NAME = "ADD_TEST_NAME",

  CREATE_NEW_SCALE = "CREATE_NEW_SCALE",
  CHANGE_SCALE_NAME = "CHANGE_SCALE_NAME",
  CHANGE_SCALE_NUMBER = "CHANGE_SCALE_NUMBER",
  DELETE_SCALE = "DELETE_SCALE",

  CREATE_NEW_QUESTION = "CREATE_NEW_QUESTION",
  CHANGE_QUESTION_NUMBER = "CHANGE_QUESTION_NUMBER",
  CHANGE_QUESTION_TEXT = "CHANGE_QUESTION_TEXT",
  DELETE_QUESTION = "DELETE_QUESTION",
  CREATE_NEW_RADIO_ANSWER = "CREATE_NEW_RADIO_ANSWER",
  CHANGE_RADIO_ANSWER_TEXT = "CHANGE_RADIO_ANSWER_TEXT",
  DELETE_RADIO_ANSWER = "DELETE_RADIO_ANSWER",
  ADD_DEPENDENCY = "ADD_DEPENDENCY",
  CHANGE_ANSWER_VALUE = "CHANGE_ANSWER_VALUE",
  CHANGE_SCALE_DEPENDENCY = "CHANGE_SCALE_DEPENDENCY",
  DELETE_DEPENDENCY = "DELETE_DEPENDENCY",

  ADD_INTERPRET = "ADD_INTERPRET",
  CHANGE_INTERPRET_TEXT = "CHANGE_INTERPRET_TEXT",
  CHANGE_INTERPRET_VALUE_LIMITS = "CHANGE_INTERPRET_VALUE_LIMITS",
  CHANGE_INTERPRET_REQUIRED_SCALE = "CHANGE_INTERPRET_REQUIRED_SCALE",
  ADD_INTERPRET_REQUIRED_SCALE = "ADD_INTERPRET_REQUIRED_SCALE",
  DELETE_INTERPRET_REQUIRED_SCALE = "DELETE_INTERPRET_REQUIRED_SCALE",
  DELETE_INTERPRET = "DELETE_INTERPRET",
  //TODO:ADD FAIL AND SUCCSESS ACTIONS
  SEND_TEST_DATA = "SEND_TEST_DATA",

  SET_TESTS_DATA = "SET_TESTS_DATA",
  INIT_TESTS = "INIT_TESTS",
  //TODO://ADD FAIL AND SUCCSESS ACTIONS
  // OTHER ACTION TYPE
  OTHER_ACTION_TYPE = "OTHER_ACTION_TYPE",
}

export default ActionTypes