export const CREATE_NEW_TEST = "CREATE_NEW_TEST";
export const ADD_TEST_NAME = "ADD_TEST_NAME";
export const CREATE_NEW_SCALE = "CREATE_NEW_SCALE";
export const CHANGE_SCALE_NAME = "CHANGE_SCALE_NAME";
export const DELETE_SCALE = "DELETE_SCALE";